### ISSUE TITLE
Any update on the topic.

### ISSUE THREAD

**Issue by isourabhkr** [exasol/row-level-security#1]
Dear Team, 
Could you kindly let us know if we can expect anything here, is this the work in progress?

Best, 
Sourabh

**Comment by redcatbear** [comment]
Hi Sourabh,

thank you for your interest in Exasol row level security. We have a PoC of row-level security based on Exasol's [Virtual Schemas](https://github.com/exasol/virtual-schemas) that was created to verify that RLS can be implemented on top of VS.

Since the PoC verified that VS is the way to go, we are now starting a production-quality implementation of row-level security (see issue #4).

Collection of requirements for a minimum viable product (MVP) is done and currently under review. Software design is in progress and we are extracting common parts of RLS and VS to a separate module in order to avoid code duplication.

Check issue #4 to stay tuned for the progress on the MV.

Let me know, if this answers your question so that I can close this issue here.

Kind regards,
Sebastian
