### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by drumcircle** [exasol/row-level-security#56]
Apologies in advance if these are obvious.  Maybe others will benefit from clarification...

1)  **Capability Parity**:  RowLevelSecurityDialect CreateCapabiliyList..addMain(…) capabilities is explicit.  Why not call:  addMain(MainCapability.values())?

2) **Complex Queries**:  Do I need to worry at all about nested queries, missing table restrictions?
 
3)  **Data Masking**: Where is the column data masking done (****)?  I’m seeing select list elements being removed but for BI, most people want the column there, content masked.  Please explain

getSelectListWithColumns(final List<TableMetadata> tableMetadata)
getColumnsFromResultSet(final ResultSet remoteColumns)
 
5)  **Adding outer SQL**: How would I rewrite the query to add a global limit filter… like SELECT * FROM <QUERY> LIMIT 10?

6)  **Exa2Exa**: When would I extend ExasolFromExaQueryRewriter rather than QueryRewriter?  Is that for a remote Exasol?

7)  **Schema/Table name rewrite**:  How would I rewrite/rename schema and table names for in database metadata, making sure to change them back at run-time?

**Comment by redcatbear** [comment]
Hi @drumcircle,

questions are always welcome.

ad 1)

Capabilities are listed explicitly in this case as a matter of precaution. If the list of MainCapabilities grows, the dialects capabilities don't automatically. Main capabilities are defined in a separate module (https://github.com/exasol/virtual-schema-common-java/blob/master/src/main/java/com/exasol/adapter/capabilities/MainCapability.java) with a separate life cycle. In case of doubt it is better the dialect reports a capability as not supported than accidentally allowing one that is not tested. 

ad 2)

RLS's capabilities are set so that the database only pushes a single `SELECT` at a time to the adapter. No joins no sub-selects. This way the adapter only ever has to deal with a single table. Joining is done on a level above RLS. While that can affect performance, it is more secure.

ad 3)

I am guessing that you mix this implementation up with another implementation. This project does not support CLS yet, so column data are never masked.

ad 4)

seems to be missing -- due to Markdown rendering?

ad 5)

If you want a limit for the results of a whole complex query, I would guess (without having that tested) a sub-select around everything should do the trick. If your question goes in a different direction, please elaborate.

ad 6)

As you correctly guessed the `ExasolFromExaQueryRewriter` is for using RLS on top of a _remote_ Exasol instance. This use case is rare -- in fact I don't know of anyone would needed it so far. Performance- and security-wise local RLS is preferable. Local RLS has the big security advantage that the data source controls the restrictions. Unless your organization owns both source and target and really needs remote-RLS, I strongly recommend using local RLS.

ad 7)

I am sorry, I don't quite get this question. Could you please rephrase it or give an example of what you are tying to achieve?

**Comment by drumcircle** [comment]
Thank you so kindly for those replies.  I'm really interested in better understanding the limitations of the framework, not necessarily the RLS implementation, in the context of writing generic rules to allow presentation of custom schema, tables and security to an authorized connection... A virtual schema of you will.  If the framework supports full rewrite of jdbc metadata and the entire sql parse tree, it would seem that sky is the limit.  Am I right?

**Comment by redcatbear** [comment]
RLS is based on Virtual Schemas. It uses the same interface towards the database. A virtual schema adapter &mdash; the part of the code that makes the extension &mdash; is at it's core a rewriter.

When you create a Virtual Schema (or refresh it), the virtual schema adapter (for example RLS) reports metadata of the source as Exasol should see it. The adapter can decide to modify that metadata. In case of RLS the control tables and columns are for example hidden.

The theoretical limitation of this concept is that the rewritten metadata must be valid. In practice, it should be close enough to the original so that you are still able to manage the necessary transformations done during SQL push-down.

A virtual schema adapter can rewrite the whole query&hellip; or at least the part that the database pushes down. In case of RLS this intentionally is only a single SELECT. The database reintegrates the rewritten part into the surrounding query. That means what you can modify is scoped. The scope depends mostly on the capabilities set in the adapter and internal query optimization.

**Comment by drumcircle** [comment]
If the source is Exasol and my physical schema (SCHEMA.TABLE/VIEW) looks like this:

PLUM1.BAR1
PLUM1.BAR2
PLUM2.BAR3

Can I present a different schema to the JDBC driver such as this?

APPLE1.BANANA1
APPLE1.BANANA2
ORANGE1.CUCUMBER1

I can see why it would be important not to conflate tables and schemas, but renaming should be OK, if we can:

1) Rename in the metadata call-back
2) Undo the rename in the Query rewriter call-back

**Comment by redcatbear** [comment]
Yes, you can.

As I said, at it's heart RLS is a [Virtual Schema](https://github.com/exasol/virtual-schemas).

Please check out the [developer information about Virtual Schemas](https://github.com/exasol/virtual-schemas#user-content-information-for-developers) about what you can do with them.

There is even a [guide to writing your own Virtual Schema](https://github.com/exasol/virtual-schemas/blob/master/doc/development/developing-sql-dialect/step_by_step_guide_to_writing_your_own_dialect.md).

**Comment by redcatbear** [comment]
Closing this issue, since questions are answered.
