### ISSUE TITLE
Blacklist for tables excluded from VS

### ISSUE THREAD

**Issue by joergbehrmann** [exasol/row-level-security#66]
Hey guys,
version 1.2.0 is working fine so far. Thank you. 
But for us it would be very helpful to have a the possibility to exclude tables from the virtual schema. We are using some technical configuration tables to filter joins. Would be great to hide these tables in the virtual schema.

Thanks,
Jörg

**Comment by redcatbear** [comment]
Hi Jörg,

happy to hear RLS works for you. There is a positive list implemented for tables. Positive lists are a lot more secure, since a new table can't accidentally slip through. You can achieve the same protection as with a negative list by simply inverting the filter.

Please check the [property `TABLE FILTER`](https://docs.exasol.com/database_concepts/virtual_schema/adapter_properties.htm). It's a comma separated list of tables a Virtual Schema takes into account.

Let me know if that works for you. I'd like to close this ticket then.

**Comment by joergbehrmann** [comment]
Hi,

thanks for the update. Since the TABLE FILTER is defined by a string, is there a limit of tables/symbols?

**Comment by redcatbear** [comment]
We are looking into the limits and are going to update the user documentation. A limit that we already can confirm is the 64 MB limit on an SQL statement. This affects the total allowed size of a `CREATE VIRTUAL SCHEMA` statement, which is the one which contains the VS properties and therefore any configuration option &mdash; like the table filter.

I will get back to you with more limits if we identify any.

**Comment by redcatbear** [comment]
The limits are as follows:

- 64 MB for the total SQL statement (`CREATE VIRTUAL SCHEMA` in this case)
- two million characters for a single Virtual Schema property (Exasol's `VARCHAR` limit)

This should still be plenty even if the positive-list of tables has a considerable amount of comma-separated entries.

@joergbehrmann, please let me know, if that answers your question, so that I can close this ticket.

**Comment by joergbehrmann** [comment]
I had no chance to build a script for creating the whitelist, but two million characters will be fine.
We are talking about table names of 20 characters tops.
So about 100k tables would be enough ;)
You can close the issue.
Thanks.

**Comment by redcatbear** [comment]
Okay, thanks for the feedback. Closing as covered.
